### ISSUE TITLE
浏览器缩放的问题

### ISSUE THREAD

**Issue by tangshiping** [erguotou520/vue-fullstack-demo#2]
用户列表页，浏览器的宽度减小时，会出现内容页中左边内容不可见，检查元素发现，app-content对应的div的位置已经左移了，被导航菜单覆盖

**Comment by erguotou520** [comment]
目测是elment-ui的问题，正在联系他们

**Comment by tangshiping** [comment]
如果基于element-ui的el-row来布局，好象不会出现这种问题。

可试一下：https://taylorchen709.github.io/vueAdmin/dist/index.html#/table

**Comment by tangshiping** [comment]
另外，检查嵌套的几个div位置发现，class为app-content的div是正确的，但是app-container就偏了

**Comment by erguotou520** [comment]
布局方式和你的稍微有些不一样，因为我的表格是占满高度的，所以要用flex布局。
另外你说的2个class正好说反了...... 其实根本原因是el-table里的table的width没变导致的

**Comment by tangshiping** [comment]
el-row也是用的flex

为什么只有app-content那个div在左移, app-container不会跟着table一起左移？

**Comment by erguotou520** [comment]
表格那边是上下位置的flex 所以el-row不行的  
在app-container的子节点加上 `width:100%`后就会发现是右边被hidden了。。。

**Comment by tangshiping** [comment]
刚试了一下在app-content的那个div上加了width:100%，竟然显示正常了，两边都不会被遮挡

**Comment by tangshiping** [comment]
仔细看了一下代码，是在ContentModule.vue里，给app-content加上了下面的css：

``
flex-flow: column;
 width: 100%;
``

**Comment by erguotou520** [comment]
嗯，确实，但是按理说它只有一个子元素，完全没必要设置这些属性的啊

**Comment by erguotou520** [comment]
[fixed](https://github.com/erguotou520/vue-fullstack-demo/commit/d24051f96caf8e5c85fdd79bf6f0dcf1a8f804d2#diff-7b3e2bb58919b8742e61a26a33f016c1L2)
